### ISSUE TITLE
Generating caption for Spanish video

### ISSUE THREAD

**Issue by cyberquarks** [abhirooptalasila/AutoSub#16]
I tested this with a Spanish video about 1:30m long and it generated a seemingly English "transliterated" text from Spanish words instead of writing the Spanish words themselves. 

Using the Spanish models from here: https://gitlab.com/Jaco-Assistant/deepspeech-polyglot#language-models-and-checkpoints

```
python3 autosub/main.py --model /home/cyberquarks/AutoSub/output_graph_es.pbmm --scorer /home/cyberquarks/AutoSub/kenlm_es.scorer --file /mnt/c/temp/test.mp4
```

Also, each sub line looks like this:

```
1
00:00:08,75 --> 00:01:30,30
```

So the subtitle covers the whole video when used with VLC

**Comment by abhirooptalasila** [comment]
I'm not sure what exactly is the issue here. Explain the first line, please. Multiple things could have gone wrong:
- The file has continuous speech audio without any gaps in which case it probably will have trouble rating its predictions properly
- The Spanish language model (scorer) is too small in my opinion. I'm not sure if they've been properly trained. Check [this](https://discourse.mozilla.org/search?q=spanish%20category%3A247)

Give me the output of your file using the DS models for English if possible.

**Comment by cyberquarks** [comment]
@abhirooptalasila  

I mean I just tested it with a sample video your YouTube: https://www.youtube.com/watch?v=jbpXP7B1U6k
Downloaded the video into MP4 and fed that to AutoSub 

I've chosen that sample video since it has a Spanish subtitle that can be compared to the processed output.

**Comment by abhirooptalasila** [comment]
I don't think there's anything wrong with the script because I just tested the video using an English model. I don't have any Spanish models so that's why I asked you to try out one of the community models attached above. I don't think the model you used the first time has been trained properly since the scorer is very small in size, which should not be the case. 

```
1
00:00:05,0: --> 00:00:08,0:
at last i saw marama history inspire

2
00:00:08,75 --> 00:00:17,30
with the opportunities in point of equanimity as he and externality as the california mexico in our

3
00:00:19,80 --> 00:00:44,45
samothrace to forcemeat noncompliance expectorated metastasis assumption ornamental baratarians malatesta allotted arlington is perfect amenities the investiture blaisencourt chop and rotomahana

4
00:00:45,55 --> 00:00:55,90
is there a six foot the toparimaca conspirator no therapeutae pitanatae baseless of man

5
00:00:58,15 --> 00:01:14,45
contamination for and to so forth and oomen iranian does facilitate the amusement as specific as paradisaical variance ostentatious parasites

6
00:01:14,85 --> 00:01:42,40
poseidonia in cut upon us bienfaisance was mistresses philosophers parthenius and for teutamenes for masculine clean anacreontic dollars existimation been seasonable time tricoteuses their position negotiation the intellectual concentration

7
00:01:42,75 --> 00:02:30,0:
executioners commonsense intemperate for any serimonious color from a practical marmosets for as declarations allow been bad companions to capacitate timocrates toronaeans of fusion illustrates a continuous marmosettes commemorative of the surintendant winterberries with pain electroplate paracelsus

8
00:02:30,75 --> 00:02:36,95
but as it is the coolness as i sat as one theoretical says there natalia

9
00:02:40,45 --> 00:02:49,55
the baserite seatoller onnecessary osteological cassandras and munitions
```

**Comment by cyberquarks** [comment]
@abhirooptalasila 

Okay, I will try that, but is there a solution for the very long subtitle line? Using it on a player makes the subtitle occupy almost all of the screen area.

**Comment by abhirooptalasila** [comment]
Need to implement #13
